package com.cafe.wsRest.mysql.model;
// Generated 28/03/2023 09:45:14 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BitacoraMysql generated by hbm2java
 */
@Entity
@Table(name="BITACORA"
    ,catalog="dbagricultor"
)
public class BitacoraMysql  implements java.io.Serializable {


     private int idBitacora;
     private String nombreTabla;
     private String idRegistro;
     private Character tipoOperacion;
     private String usuarioCreacion;
     private Date fechaCreacion;

    public BitacoraMysql() {
    }

	
    public BitacoraMysql(int idBitacora) {
        this.idBitacora = idBitacora;
    }
    public BitacoraMysql(int idBitacora, String nombreTabla, String idRegistro, Character tipoOperacion, String usuarioCreacion, Date fechaCreacion) {
       this.idBitacora = idBitacora;
       this.nombreTabla = nombreTabla;
       this.idRegistro = idRegistro;
       this.tipoOperacion = tipoOperacion;
       this.usuarioCreacion = usuarioCreacion;
       this.fechaCreacion = fechaCreacion;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="ID_BITACORA")
    public int getIdBitacora() {
        return this.idBitacora;
    }
    
    public void setIdBitacora(int idBitacora) {
        this.idBitacora = idBitacora;
    }

    
    @Column(name="NOMBRE_TABLA", length=30)
    public String getNombreTabla() {
        return this.nombreTabla;
    }
    
    public void setNombreTabla(String nombreTabla) {
        this.nombreTabla = nombreTabla;
    }

    
    @Column(name="ID_REGISTRO", length=40)
    public String getIdRegistro() {
        return this.idRegistro;
    }
    
    public void setIdRegistro(String idRegistro) {
        this.idRegistro = idRegistro;
    }

    
    @Column(name="TIPO_OPERACION", length=1)
    public Character getTipoOperacion() {
        return this.tipoOperacion;
    }
    
    public void setTipoOperacion(Character tipoOperacion) {
        this.tipoOperacion = tipoOperacion;
    }

    
    @Column(name="USUARIO_CREACION", length=50)
    public String getUsuarioCreacion() {
        return this.usuarioCreacion;
    }
    
    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHA_CREACION", length=19)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }




}


